robots:
  robot1:
    host: 127.0.0.1
    dashboard_port: 29991
    script_port: 30022
    ssh_port: 2222
    ssh_username: root
    ssh_password: easybot
    enabled: true
    assigned_program: library://hello-78c94d3f
  robot2:
    host: 127.0.0.1
    dashboard_port: 29992
    script_port: 30022
    ssh_port: 22
    ssh_username: root
    ssh_password: easybot
    enabled: false
    assigned_program: library://hello-78c94d3f
  robot3:
    host: 127.0.0.1
    dashboard_port: 29993
    script_port: 30023
    ssh_port: 22
    ssh_username: root
    ssh_password: easybot
    enabled: false
    assigned_program: null
